
spring:
  application:
    name: dubbo-provider-demo

dubbo:
  application:
    name: test-server
  consumer:
    check: false
  registry:
    address: nacos://localhost:8848  # Nacos地址
    parameters:
      namespace: public    # 可选命名空间
    password: nacos
    username: nacos
    check: false
  protocol:
    name: dubbo     # 使用Dubbo协议
    port: 20880     # 服务暴露端口
  scan:
    base-packages: com.example.test.service.impl

server:
  port: 8082
  tomcat:
    threads:
      max: 200
    max-connections: 1000000
#cbc:
#  rpc:
#    nacos:
#      registry:
#        port: 8086
#        server-name: s2

